# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: hand
  joint_model_group_pose: p1
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - base_to_prox_t
    - prox_to_distal_t
    - base_to_rot_l
    - rot_to_prox_l
    - prox_to_distal_l
    - base_to_rot_r
    - rot_to_prox_r
    - prox_to_distal_r
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - base_to_prox_t
      - prox_to_distal_t
      - base_to_rot_l
      - rot_to_prox_l
      - prox_to_distal_l
      - base_to_rot_r
      - rot_to_prox_r
      - prox_to_distal_r
hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_to_prox_t
    - prox_to_distal_t
    - base_to_rot_l
    - rot_to_prox_l
    - prox_to_distal_l
    - base_to_rot_r
    - rot_to_prox_r
    - prox_to_distal_r
  gains:
    base_to_prox_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    prox_to_distal_t:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base_to_rot_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rot_to_prox_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    prox_to_distal_l:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    base_to_rot_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    rot_to_prox_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    prox_to_distal_r:
      p: 100
      d: 1
      i: 1
      i_clamp: 1